## Numpy Basics

In [1]:
!pip install numpy

You are using pip version 19.0.3, however version 19.2.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [3]:
import numpy as np

In [4]:
np.abs(-5)

5

In [16]:
# Numpy Arrays
a = np.array([1,2,3,4,5]) 
a = a*5 + 1 #Broadcasting (Vector + Scalar)
print(a)
print(type(a))

[ 6 11 16 21 26]
<class 'numpy.ndarray'>


In [17]:
# Another Attribute
print(a.shape)

(5,)


In [31]:
b = np.array([[1,2,3],[4,5,6]])

print(b.shape)
print(b)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [32]:
# Transpose of Array
b = b.T
print(b.shape)
print(b)

(3, 2)
[[1 4]
 [2 5]
 [3 6]]


In [38]:
# Indexing
b[0][1]

4

In [50]:
# Reshape
b = b.reshape((1,6))

In [51]:
print(b)
print(b.shape)

[[1 4 2 5 3 6]]
(1, 6)


In [53]:
b[0][0]

1

In [54]:
# Some Special Matrices
# Ones
# Zeroes
# Diagonal 

In [71]:
z = np.zeros(shape = (5,5),dtype='int')
print(z)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [72]:
z[1:3,2:4] = 5
print(z)

[[0 0 0 0 0]
 [0 0 5 5 0]
 [0 0 5 5 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [75]:
# Tuple Unpacking
m,n = z.shape
print(m,n)
# Iterate Over Matrix
for i in range(m):
    for j in range(n):
        if i>j:
            z[i,j] = 7
            
print(z)

5 5
[[0 0 0 0 0]
 [7 0 5 5 0]
 [7 7 5 5 0]
 [7 7 7 0 0]
 [7 7 7 7 0]]


In [77]:
# Matrix Multiplication (Dot Product)
result = np.dot(z,z)
print(result)

[[  0   0   0   0   0]
 [ 70  70  60  25   0]
 [119  70  95  60   0]
 [ 98  49  70  70   0]
 [147  98 119  70   0]]


In [81]:
# Determinant
a = np.array([[1,2],
              [3,4]])
det = np.linalg.det(a)
print(np.round(det))

-2.0


In [86]:
# Psudeo Inverse
a_inv = np.linalg.pinv(a)
print(a_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [87]:
np.round(np.dot(a,a_inv))

array([[ 1., -0.],
       [ 0.,  1.]])

In [96]:
# Matrix of Ones
ones = np.ones((5,3),dtype='int')
ones = ones*5
v = np.array([1,2,3])
print(ones+v) # Matrix + Vector Addition (Broadcasting)
#print(ones)

[[6 7 8]
 [6 7 8]
 [6 7 8]
 [6 7 8]
 [6 7 8]]


In [106]:
# Diagonal Matrix -> Always a Square Matrix
I = np.eye(5,dtype='int')
print(I*3)

[[3 0 0 0 0]
 [0 3 0 0 0]
 [0 0 3 0 0]
 [0 0 0 3 0]
 [0 0 0 0 3]]


In [102]:
# Random Integers Matrix
print(np.random.randint(10,20,4))

[19 14 13 14]


In [104]:
print(np.random.randint(10,20,(4,3)))

[[14 18 19]
 [12 14 10]
 [14 13 13]
 [14 16 16]]


In [115]:
np.random.seed(5)

In [113]:
print(np.random.randint(30,40,1))

[33]


In [116]:
print(np.random.randint(30,40,1))

[33]
